package db

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	"vot-tradings/internal/models"
)

type OrderStore struct {
	pool *pgxpool.Pool
}

func NewOrderStore(pool *pgxpool.Pool) *OrderStore {
	return &OrderStore{pool: pool}
}

// Create persists an order the gateway has already submitted to (or had
// rejected by) the broker. id should be a fresh UUID generated by the
// caller.
func (s *OrderStore) Create(ctx context.Context, id string, o models.Order) error {
	_, err := s.pool.Exec(ctx, `
		INSERT INTO orders (id, user_id, broker, symbol, side, type, quantity, limit_price, status, broker_order_id, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
	`, id, o.UserID, o.Broker, o.Symbol, o.Side, o.Type, o.Quantity, o.LimitPrice, o.Status, o.BrokerOrderID, o.CreatedAt, o.UpdatedAt)
	if err != nil {
		return fmt.Errorf("db: create order: %w", err)
	}
	return nil
}

// ListByUser returns a user's orders, most recent first.
func (s *OrderStore) ListByUser(ctx context.Context, userID string) ([]models.Order, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, user_id, broker, symbol, side, type, quantity, limit_price, status, broker_order_id, created_at, updated_at
		FROM orders
		WHERE user_id = $1
		ORDER BY created_at DESC
	`, userID)
	if err != nil {
		return nil, fmt.Errorf("db: list orders: %w", err)
	}
	defer rows.Close()

	var orders []models.Order
	for rows.Next() {
		var o models.Order
		if err := rows.Scan(&o.ID, &o.UserID, &o.Broker, &o.Symbol, &o.Side, &o.Type, &o.Quantity, &o.LimitPrice, &o.Status, &o.BrokerOrderID, &o.CreatedAt, &o.UpdatedAt); err != nil {
			return nil, fmt.Errorf("db: scan order: %w", err)
		}
		orders = append(orders, o)
	}
	return orders, rows.Err()
}
