package db

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"vot-tradings/internal/models"
)

// postgresUniqueViolation is the SQLSTATE code Postgres returns for a
// unique-constraint conflict (e.g. a duplicate email).
const postgresUniqueViolation = "23505"

// ErrUserNotFound is returned by UserStore lookups that find no matching row.
var ErrUserNotFound = errors.New("db: user not found")

// ErrEmailTaken is returned by CreateUser when the email is already
// registered.
var ErrEmailTaken = errors.New("db: email already registered")

type UserStore struct {
	pool *pgxpool.Pool
}

func NewUserStore(pool *pgxpool.Pool) *UserStore {
	return &UserStore{pool: pool}
}

// CreateUser inserts a new user with an already-hashed password. id should
// be a fresh UUID generated by the caller.
func (s *UserStore) CreateUser(ctx context.Context, id, email, passwordHash string) (models.User, error) {
	var u models.User
	err := s.pool.QueryRow(ctx, `
		INSERT INTO users (id, email, password_hash)
		VALUES ($1, $2, $3)
		RETURNING id, email, password_hash, created_at
	`, id, email, passwordHash).Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == postgresUniqueViolation {
			return models.User{}, ErrEmailTaken
		}
		return models.User{}, fmt.Errorf("db: create user: %w", err)
	}
	return u, nil
}

func (s *UserStore) GetUserByEmail(ctx context.Context, email string) (models.User, error) {
	var u models.User
	err := s.pool.QueryRow(ctx, `
		SELECT id, email, password_hash, created_at FROM users WHERE email = $1
	`, email).Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return models.User{}, ErrUserNotFound
	}
	if err != nil {
		return models.User{}, fmt.Errorf("db: get user by email: %w", err)
	}
	return u, nil
}

func (s *UserStore) GetUserByID(ctx context.Context, id string) (models.User, error) {
	var u models.User
	err := s.pool.QueryRow(ctx, `
		SELECT id, email, password_hash, created_at FROM users WHERE id = $1
	`, id).Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return models.User{}, ErrUserNotFound
	}
	if err != nil {
		return models.User{}, fmt.Errorf("db: get user by id: %w", err)
	}
	return u, nil
}
